{{- if .Values.runtime.nvidia.enabled }}
---
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: {{ include "jellyfin.fullname" . }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
handler: nvidia
{{- end }}
