---
enabled: false

replicaCount: 1

image:
  repository: vexorian/dizquetv
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

env: []
## Nvidia GPU
# - name: NVIDIA_VISIBLE_DEVICES
#   value: "all"

runtime:
  nvidia:
    enabled: false

resources: {}
## Intel GPU
# requests:
#     gpu.intel.com/i915: "0"
# limits:
#     gpu.intel.com/i915: "0"

## Nvidia GPU
# requests:
#     nvidia.com/gpu: "0"
# limits:
#     nvidia.com/gpu: "0"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector:
  {}
  ## Deploy on nodes with specific GPU
  ## Intel GPU
  # gpu: "intel"

  ## Nvidia GPU
  # gpu: "nvidia"

tolerations: []
affinity: {}
