apiVersion: v2
name: media-stack
description: A Helm chart for Kubernetes for deploying media applications
type: application
version: 0.0.2
appVersion: latest
dependencies:
  - condition: sonarr.enabled
    name: sonarr
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: radarr.enabled
    name: radarr
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: prowlarr.enabled
    name: prowlarr
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: bazarr.enabled
    name: bazarr
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: overseerr.enabled
    name: overseerr
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: transmission.enabled
    name: transmission
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: plex.enabled
    name: plex
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: tautulli.enabled
    name: tautulli
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: tautulli-exporter.enabled
    name: tautulli-exporter
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: dizquetv.enabled
    name: dizquetv
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: jellyfin.enabled
    name: jellyfin
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: bazarr.enabled
    name: bazarr
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
  - condition: flaresolverr.enabled
    name: flaresolverr
    version: 0.0.1
    repository: https://geekxflood.github.io/helm-charts/
icon: file://assets/icon.png
keywords:
  - kubernetes
  - media
  - sonarr
  - radarr
  - bazarr
  - overseerr
  - transmission
  - plex
  - tautulli
  - linuxserver
maintainers:
  - name: geekxflood
