{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tautulli-exporter.fullname" . }}
  labels:
    {{- include "tautulli-exporter.labels" . | nindent 4 }}
spec:
  endpoints:
  - honorLabels: true
    port: http
  jobLabel: tautulli-exporter
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      name: {{ include "tautulli-exporter.fullname" . }}
{{- end }}
